### ISSUE TITLE
ADMIN REPORT 

### ISSUE THREAD

**Issue by PoliceComputer22** [Loikas/PlateCheckerRemasterd#2]
NOT FOLLOWING INTERACTION

**Comment by Loikas** [comment]
Could you use this for issues regarding the programming of the plugin? And not stories of npcs.

**Comment by PoliceComputer22** [comment]
> Could you use this for issues regarding the programming of the plugin? And not stories of npcs.

WHAT WRONG WITH NPC'S

**Comment by Loikas** [comment]
This is not the placs

**Comment by PoliceComputer22** [comment]
ITS FOR GTAV...CALM DOWN
