### ISSUE TITLE
LSPD REPORT 

### ISSUE THREAD

**Issue by PoliceComputer22** [Loikas/PlateCheckerRemasterd#3]
REASON: CAR ACCIDENT
COURSE BY DRINK AND DRIVING 
DRIVER IS UNDER WEED
AND ACHOLICO
LICENSE PLATE:49WSI191 
STOLEN LICENSE PLATES 
CAR MAYBE STOLEN

**Comment by Loikas** [comment]
Dude find someplace else for these messages.
Go to the lspdfr forum or something please.

**Comment by PoliceComputer22** [comment]
FUCK OFF JUST INORE IT ...NOT FOR YOU .. JUST DON'T REPLY SIMPLE

**Comment by Loikas** [comment]
Then dont post it in MY github issues that should be used for issues about MY plugin
